import { generateRandomSlug } from "@/utils/helper";

export const COOKIE_NAME = "tenant";

export type Property = {
  id: string;
  category: string;
  slug: string;
  address: string;
  pricePerMonth: number;
  bedrooms: number;
  bathrooms: number;
  sqft: number;
  images: string[];
  amenities: string[];
  description: string;
  contactEmail: string;
  contactPhone: string;
};

export type City = {
  id: string;
  name: string;
  state: string;
  heroImage: string;
  properties: Property[];
};

export const cities: City[] = [
  {
    id: "alameda",
    name: "Alameda",
    state: "California",
    heroImage: "/alameda.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "2932 Marina Dr, Alameda, CA 94501",
        pricePerMonth: 4713,
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1851,
        images: [
          "/properties/alameda-1-1.webp",
          "/properties/alameda-1-2.webp",
          "/properties/alameda-1-3.webp",
          "/properties/alameda-1-4.webp",
          "/properties/alameda-1-5.webp",
          "/properties/alameda-1-6.webp",
        ],
        amenities: [
          "3 Bedrooms",
          "3 Bathrooms",
          "Basement",
          "Wood Burning Fireplace",
          "Attached Garage",
          "2 Garage Spaces",
          "Patio",
          "Mid Century Modern",
        ],
        description:
          "Discover the perfect blend of 1940s craftsmanship and modern versatility in the heart of Alameda’s coveted East End. This spacious 3 bedroom, 2.25 bathroom home offers 1,851 square feet of living space on a 4,879 square foot lot, capturing the essence of “Old Alameda” while providing the flexibility today’s buyers demand. Step across original gleaming wood floors into a residence rich with period details, from inviting living areas to sun-drenched bedrooms that create a warm, timeless foundation for any personal style. ",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "142 Coronado Ave, Alameda, CA 94501",
        pricePerMonth: 5711,
        bedrooms: 4,
        bathrooms: 4,
        sqft: 1851,
        images: [
          "/properties/alameda-2-1.webp",
          "/properties/alameda-2-2.webp",
          "/properties/alameda-2-3.webp",
          "/properties/alameda-2-4.webp",
          "/properties/alameda-2-5.webp",
          "/properties/alameda-2-6.webp",
        ],
        amenities: [
          "4 Bedrooms",
          "4 Bathrooms",
          "4 Full Bathrooms",
          "Ground Floor Bedroom",
          "Walk-In Closet",
          "Double Sinks",
          "Dual Flush Toilet",
          "Shower Over Tub",
          "Dining Area",
        ],
        description:
          "Rare 2.5% assumable rate mortgage opportunity* Discover elevated living in this upgraded 4 bed, 4 bath condo built in 2022. Street facing with rare privacy, no front neighbors, open park views, and abundant natural light. The flexible multilevel layout begins with a first floor bedroom and ensuite bath featuring soaring 14 foot ceilings, ideal for guests, a home office, or multigenerational living",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "atlanta",
    name: "Atlanta",
    state: "Georgia",
    heroImage: "/atl.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "1356 Wylie St SE Lot 0, Atlanta, GA 30317",
        pricePerMonth: 1876,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2471,
        images: [
          "/properties/atl-1-1.webp",
          "/properties/atl-1-2.webp",
          "/properties/atl-1-3.webp",
          "/properties/atl-1-4.webp",
          "/properties/atl-1-5.webp",
          "/properties/atl-1-6.webp",
        ],
        amenities: [
          "4 Bedrooms",
          "3 Bathrooms",
          "Kitchen Island",
          "Walk-In Closet",
          "Hardwood Flooring",
          "Gas Log Fireplace",
          "Central Air",
          "Attached Garage",
        ],
        description:
          "Gorgeous modern Craftsman in the heart of Edgewood-just steps from the new Trolley Line Trail connecting directly to the Atlanta BeltLine! Ideally located minutes from the shops and restaurants of Pullman Yards and the Kirkwood Business District, as well as Coan Park and the MARTA station. This home features a thoughtful design with a welcoming front porch, open floor plan, hardwood floors, and custom blinds throughout. The gourmet kitchen is complete with custom cabinetry, quartz countertops, stainless steel appliances with gas cooking, a large island, and a butler's pantry with butcher-block countertop and adjoining mudroom. The sun-filled living room boasts a wall of windows overlooking the backyard, a beamed ceiling, and a gas-log fireplace.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "783 Auguste Ave, Scottdale, GA 30079",
        pricePerMonth: 1099,
        bedrooms: 4,
        bathrooms: 4,
        sqft: 2265,
        images: [
          "/properties/atl-2-1.webp",
          "/properties/atl-2-2.webp",
          "/properties/atl-2-3.webp",
          "/properties/atl-2-4.webp",
          "/properties/atl-2-5.webp",
          "/properties/atl-2-6.webp",
        ],
        amenities: [
          "4 Bedrooms",
          "4 Bathrooms",
          "Kitchen Island",
          "Walk-In Pantry",
          "Double Vanity",
          "High Ceilings",
          "Walk-In Closets",
          "Gas Fireplace",
        ],
        description:
          "Celesta is a brand new community by David Weekley Homes and features 80 detached townhouse style homes with 2-car garages. All homes have 3 levels, with a guest bedroom on the garage level and either 2 or 3 more bedrooms on the top floor. This home is our Brexton plan and will have 4 bedrooms and 3.5 bathrooms. Built with a focus on spacious living areas and closets, these detached craftsman style homes will ensure a quiet and comfortable place to come home to after a busy day at the office or a night out on the town. These new construction homes are being built using EnergySaver Home techniques to minimize energy consumption and reduce environmental impact. Features includes 2x6 exterior framed walls with 50% more insulation than a 2x4 wall, and tankless water heaters. Come enjoy high-end living and incredible convenience for the right price. Celesta is just minutes from Downtowns Decatur, Avondale Estates, and Toco Hills and is surrounded by endless shopping and restaurants. In Addition and coming soon, just 1 mile down the road will be the new mixed-use shopping destination called Lulah Hills.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "austin",
    name: "Austin",
    state: "Texas",
    heroImage: "/austin.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "2704 Mountain Laurel Dr, Austin, TX 78703",
        pricePerMonth: 7000,
        bedrooms: 5,
        bathrooms: 6,
        sqft: 4665,
        images: [
          "/properties/austin-1-1.webp",
          "/properties/austin-1-2.webp",
          "/properties/austin-1-3.webp",
          "/properties/austin-1-4.webp",
          "/properties/austin-1-5.webp",
          "/properties/austin-1-6.webp",
        ],
        amenities: [
          "5 Bedrooms",
          "6 Bathrooms",
          "Kitchen Island",
          "Breakfast Bar",
          "High Ceilings",
          "Walk-In Closets",
          "Soaking Tub",
          "Gas Fireplace",
        ],
        description:
          "Introducing a breathtaking estate by visionary architect Patrick Ousey of FAB Architecture- an inspired one-story contemporary residence that redefines refined living in central Austin's most coveted neighborhood, Tarrytown, zoned to & steps away from the highly rated Casis Elementary (10/10 on Greatschools). Set on a rare 13,037 sq.ft. lot, this architectural gem seamlessly blends warm modernism with functional elegance, delivering a private sanctuary. Encompassing approximately 4,665 sqft, the home unfolds with curated intention every detail tailored for elevated everyday living.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "4216 Deepwoods Dr, Austin, TX 78731",
        pricePerMonth: 5300,
        bedrooms: 5,
        bathrooms: 5,
        sqft: 4015,
        images: [
          "/properties/austin-2-1.webp",
          "/properties/austin-2-2.webp",
          "/properties/austin-2-3.webp",
          "/properties/austin-2-4.webp",
          "/properties/austin-2-5.webp",
          "/properties/austin-2-6.webp",
        ],
        amenities: [
          "4 Bedrooms",
          "4 Bathrooms",
          "Kitchen Island",
          "Walk-In Pantry",
          "Double Vanity",
          "High Ceilings",
          "Walk-In Closets",
          "Gas Fireplace",
        ],
        description:
          "This newly completed 4,015-square-foot luxury residence in Northwest Hills is move-in ready and thoughtfully designed for elevated living. The main level features an exceptionally private and expansive primary suite, offering a true retreat with generous proportions and refined finishes. A secondary bedroom on the main floor, complete with a full bath, provides ideal flexibility for guest accommodations or a sophisticated home office. Soaring 22-foot ceilings lined with dramatic walls of windows flood the home with extraordinary natural light, creating an open and airy atmosphere rarely found in residential construction. ",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "chicago",
    name: "Chicago",
    state: "Illinois",
    heroImage: "/chicago.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "2036 W Farragut Ave, Chicago, IL 60625",
        pricePerMonth: 6098,
        bedrooms: 6,
        bathrooms: 2,
        sqft: 1245,
        images: [
          "/properties/chicago-1-1.webp",
          "/properties/chicago-1-2.webp",
          "/properties/chicago-1-3.webp",
          "/properties/chicago-1-4.webp",
          "/properties/chicago-1-5.webp",
          "/properties/chicago-1-6.webp",
        ],
        amenities: [
          "Enclosed Porch",
          "Utility Room (Lower Level)",
          "Finished Basement",
          "Natural Gas Heating",
          "Screens on Windows",
          "Garage Owned / Detached",
          "Garage Door Opener",
          "Uncovered Parking Spaces",
        ],
        description:
          "Exceptionally well-maintained 2-flat with a garden-level in-law apartment situated on a tree-lined street in a prime location. This building offers endless possibilities as a terrific investment property or a home for an owner-occupant. The wide lot creates large units that blend vintage details with beautiful updates. Both units are flooded with natural light and showcase hardwood floors, elegant original woodwork, decorative brick fireplaces, updated baths, and expansive hallways. Each unit has 3 bedrooms plus enclosed porches, making them perfect for the 'work from home' buyer. Both apartments have large formal dining rooms and beautifully renovated kitchens with 42-inch cabinets, granite counters, custom backsplash, stainless steel appliances, and a pantry nook.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "42208 N Burling St, Chicago, IL 60614",
        pricePerMonth: 4500,
        bedrooms: 4,
        bathrooms: 2,
        sqft: 4015,
        images: [
          "/properties/chicago-2-1.webp",
          "/properties/chicago-2-2.webp",
          "/properties/chicago-2-3.webp",
          "/properties/chicago-2-4.webp",
          "/properties/chicago-2-5.webp",
          "/properties/chicago-2-6.webp",
        ],
        amenities: [
          "Hardwood Flooring",
          "Granite Counters",
          "Updated Kitchen",
          "Central Air",
          "Natural Gas Heating",
          "In-Unit Laundry",
          "Stainless Steel Appliances",
          "Storage / Bonus Rooms",
        ],
        description:
          "Nestled on one of Lincoln Park's most picturesque, tree-lined blocks, directly across from the storybook charm of Oz Park, 2208 N Burling Street is available for the first time in more than thirty years. This four-bedroom, two-bath townhome blends the character of its classic Chicago setting with thoughtful modern updates, creating a home that feels both timeless and refreshingly current.    Inside, newly installed hardwood floors lead you through an open, inviting layout where the living room, dining area, and kitchen flow seamlessly together. A wood-burning fireplace anchors the space, adding warmth and comfort, while sliding glass doors open to a lush private garden patio-a rare urban retreat perfect for relaxing, grilling, or dining al fresco beneath the trees. The kitchen has been remodeled with sleek new cabinetry, stone counters and backsplash, modern appliances, and ample counter space designed for both everyday living and entertaining.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "denver",
    name: "Denver",
    state: "Charlotte",
    heroImage: "/denver.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "1775 Mount Carmel Cir, Denver, NC 28037",
        pricePerMonth: 3166,
        bedrooms: 5,
        bathrooms: 5,
        sqft: 4368,
        images: [
          "/properties/denver-1-1.webp",
          "/properties/denver-1-2.webp",
          "/properties/denver-1-3.webp",
          "/properties/denver-1-4.webp",
          "/properties/denver-1-5.webp",
          "/properties/denver-1-6.webp",
        ],
        amenities: [
          "Primary Bedroom with En Suite Bathroom",
          "Ceiling Fans",
          "Kitchen Island",
          "Open Floorplan",
          "Forced Air & Heat Pump Heating",
          "Zoned Electric & Heat Pump Cooling",
          "Finished Basement with Bar/Entertainment Area",
          "Attached Garage with 2 Spaces",
        ],
        description:
          "You'll love this spacious one-owner 5-bedroom, 5-bathroom home located on quiet Mt. Carmel Circle in Denver’s highly desirable Verdict Ridge community. Perfectly set on a peaceful, wooded lot, this residence offers comfort, privacy, and room to spread out—all while being just minutes from Lake Norman, shopping, dining, and major commuter routes into Charlotte.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "8022 Silver Jade Ln, Denver, NC 28037",
        pricePerMonth: 7812,
        bedrooms: 5,
        bathrooms: 3,
        sqft: 3553,
        images: [
          "/properties/denver-2-1.webp",
          "/properties/denver-2-2.webp",
          "/properties/denver-2-3.webp",
          "/properties/denver-2-4.webp",
          "/properties/denver-2-5.webp",
          "/properties/denver-2-6.webp",
        ],
        amenities: [
          "Primary Bedroom on Upper Level",
          "Central Heating (Natural Gas)",
          "Central Air Conditioning (Electric)",
          "Fireplace with Gas",
          "Attached Garage with 3 Spaces",
          "In-ground Fenced Pool",
          "Boat Slip on Lake Norman",
          "Laundry Room",
        ],
        description:
          "Stop dreaming and start living the ultimate Sailview lifestyle in this stunning 5-bedroom, full-brick estate, which has been meticulously updated and is ready for its next chapter; and yes, it comes with its very own DEEDED BOAT SLIP (6-A Slip 58)! From the moment you enter, you’ll notice the sophisticated details that set this home apart, including elegant formal living and dining rooms with tray ceilings, flowing seamlessly into a light-filled family room with a fireplace and a remodeled chef’s kitchen that is truly a showstopper. Upstairs, discover five generous bedrooms, including a primary suite that feels like a five-star spa with a deep-soak jacuzzi tub, oversized walk-in shower, and double vanities.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "houston",
    name: "Houston",
    state: "Texas",
    heroImage: "/houston.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "2604-2606 Winbern St, Houston, TX 77004",
        pricePerMonth: 2817,
        bedrooms: 3,
        bathrooms: 3,
        sqft: 4000,
        images: [
          "/properties/houston-1-1.webp",
          "/properties/houston-1-2.webp",
          "/properties/houston-1-3.webp",
          "/properties/houston-1-4.webp",
          "/properties/houston-1-5.webp",
          "/properties/houston-1-6.webp",
        ],
        amenities: [
          "3 Bedrooms",
          "3 Full Bathrooms",
          "Natural Gas Heating (Zoned)",
          "Electric Cooling (Zoned)",
          "ENERGY STAR Qualified Appliances",
          "Disposal, Microwave, Dishwasher",
          "Flooring: Carpet, Tile, Vinyl",
          "Insulated/Low-E Windows",
        ],
        description:
          "Andares Homes brings a modern Duplex to Third Ward. This beautiful investment stands out with its sleek and modern finishes. The home offers a striking exterior, complemented by oversized windows, allowing for plenty of natural light to flow through. Inside, an open-concept living and kitchen space flows seamlessly, with thoughtful details such as gold hardware, luxury fixtures, and a clay farm sink. Step into the serene primary room, complete with a custom-designed suite featuring double vanities, a frameless glass shower, and a freestanding soaking tub for relaxation. Every detail has been meticulously crafted, from the sleek imported tiles to the designer lighting, giving the home a truly elevated feel. Located minutes from downtown Houston, this home provides the perfect combination of luxury and location, making it a rare find in the current market.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "14103 Carolcrest Cir, Houston, TX 77079",
        pricePerMonth: 12166,
        bedrooms: 5,
        bathrooms: 6,
        sqft: 4836,
        images: [
          "/properties/houston-2-1.webp",
          "/properties/houston-2-2.webp",
          "/properties/houston-2-3.webp",
          "/properties/houston-2-4.webp",
          "/properties/houston-2-5.webp",
          "/properties/houston-2-6.webp",
        ],
        amenities: [
          "5 Beds",
          "6 Baths",
          "Den",
          "Utility Room",
          "Primary Bath: Double Sinks, Jetted Tub, Separate Shower",
          "Secondary Baths: Shower Only, Tub/Shower Combo, Half Bath",
          "Kitchen: Island, Breakfast Bar, Pot Filler, Soft Close Cabinets/Drawers, Under Cabinet Lights, Walk-in Pantry",
        ],
        description:
          "Stunning residence nestled on a quiet cul-de-sac in Memorial, featuring high-end finishes throughout. The open-concept layout showcases soaring ceilings, herringbone wood floors, and abundant natural light. The gourmet kitchen is equipped with custom cabinetry, stainless steel appliances, and a spacious island—ideal for gatherings. The luxurious primary suite offers a spa-like bath and an oversized fashionista closet. A secondary bedroom with full bath is located downstairs, perfect for guests. Step outside to your private outdoor oasis with a covered kitchen, heated pool, and multiple lounge areas—ideal for effortless entertaining. Notable upgrades include automatic blinds, an in-home water purifier, new ACs, new pool equipment and a full sprinkler system. Prime location just minutes from I-10, Beltway 8, and Westpark Tollway, with close proximity to CityCentre, Memorial City Mall, and premier dining and shopping.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "las-vegas",
    name: "Las Vegas",
    state: "Nevada",
    heroImage: "/lv.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "7477 Ullom Dr, Las Vegas, NV 89139",
        pricePerMonth: 4167,
        bedrooms: 5,
        bathrooms: 3,
        sqft: 2840,
        images: [
          "/properties/nevada-1-1.webp",
          "/properties/nevada-1-2.webp",
          "/properties/nevada-1-3.webp",
          "/properties/nevada-1-4.webp",
          "/properties/nevada-1-5.webp",
          "/properties/nevada-1-6.webp",
        ],
        amenities: [
          "5 Beds",
          "3 Baths",
          "Kitchen Island",
          "Quartz Counters",
          "Vaulted Ceiling",
          "Luxury Vinyl Plank Flooring",
          "Wood Burning Fireplace",
          "RV Access / Hookups",
        ],
        description:
          "Fully remodeled 5-bedroom, 3-bath home on a rare 22,000+ sq ft cul-de-sac lot with no HOA and horse zoning, ideal for out-of-state buyers relocating to Las Vegas or locals seeking land and RV access. Located near Allegiant Stadium with easy freeway access. Interior features include luxury laminate flooring, 5” baseboards, decorative ceilings, and custom stone accents. The upgraded kitchen offers quartz countertops, new cabinetry, stainless steel appliances, and a canopy range hood. The main level includes a bedroom, full bath, and den, ideal for guests or multi-gen living. Bathrooms feature modern tile, sleek vanities, smart toilets, and glass showers.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "372 Beesley Dr, Sunrise Manor, NV 89110",
        pricePerMonth: 5617,
        bedrooms: 4,
        bathrooms: 4,
        sqft: 3901,
        images: [
          "/properties/nevada-2-1.webp",
          "/properties/nevada-2-2.webp",
          "/properties/nevada-2-3.webp",
          "/properties/nevada-2-4.webp",
          "/properties/nevada-2-5.webp",
          "/properties/nevada-2-6.webp",
        ],
        amenities: [
          "4 Beds",
          "4 Baths",
          "Primary Suite Downstairs",
          "Granite Counters",
          "Kitchen Island",
          "Multi-Sided Fireplace",
          "Private In-Ground Pool",
          "4-Car Garage with RV Access",
        ],
        description:
          "This stunning single-story custom home, built in 2017, sits on an expansive ¾-acre lot and offers the perfect blend of luxury, space, and functionality. Featuring 4 spacious bedrooms, 3 well-appointed bathrooms, and a dedicated den, the open layout is ideal for both everyday living and entertaining. The heart of the home showcases granite countertops, abundant cabinetry, and tile flooring throughout for a clean, modern look and easy maintenance. A 4-car garage provides ample room for vehicles, storage, or hobbies. Step outside to your private oasis with a sparkling pool, massive backyard, and a fully equipped outdoor kitchen—perfect for hosting gatherings or enjoying quiet evenings.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "los-angeles",
    name: "Los Angeles",
    state: "California",
    heroImage: "/alameda.avif",
    properties: [
      {
        id: "1",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "27616 Suncrest Rd, San Pedro, CA 90732",
        pricePerMonth: 7501,
        bedrooms: 5,
        bathrooms: 5,
        sqft: 3527,
        images: [
          "/properties/los-1-1.webp",
          "/properties/los-1-2.webp",
          "/properties/los-1-3.webp",
          "/properties/los-1-4.webp",
          "/properties/los-1-5.webp",
          "/properties/los-1-6.webp",
        ],
        amenities: [
          "5 Beds",
          "5 Baths",
          "Heated In-Ground Pool & Spa",
          "Harbor & Bridge Views",
          "Kitchen Island with Quartz Counters",
          "Owned Solar System",
          "Smart Home Features",
          "Gated Community with HOA Amenities",
        ],
        description:
          "Located in the exclusive gated community of Ponte Vista, this luxury estate model home offers unobstructed harbor and bridge views with premium upgrades throughout. Built in 2020, the residence features 5 bedrooms and 5 bathrooms across 3,527 square feet of thoughtfully designed living space. The open-concept layout showcases hardwood flooring, floor-to-ceiling soft-close cabinetry, quartz countertops, and a chef’s kitchen equipped with a 6-burner stove, double ovens, and high-end appliances. Step outside to a beautifully landscaped backyard with a heated in-ground pool, spa, fire pit, and BBQ area—perfect for entertaining. Additional highlights include a 16-panel owned solar system, smart home technology, and access to resort-style HOA amenities including a fitness center, dog park, trails, and recreation areas.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Downtown Residences",
        slug: generateRandomSlug(),
        address: "19253 Kenya St, Porter Ranch, CA 91326",
        pricePerMonth: 5788,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2427,
        images: [
          "/properties/los-2-1.webp",
          "/properties/los-2-2.webp",
          "/properties/los-2-3.webp",
          "/properties/los-2-4.webp",
          "/properties/los-2-5.webp",
          "/properties/los-2-6.webp",
        ],
        amenities: [
          "4 Beds",
          "3 Baths",
          "Sparkling Private Pool",
          "Soaring High Ceilings",
          "Granite Kitchen Counters",
          "Cozy Living Room Fireplace",
          "Large Pantry & Sub-Zero Fridge",
          "2-Car Garage + Driveway Parking",
        ],
        description:
          "This beautifully maintained tri-level Porter Ranch home offers 4 spacious bedrooms and 3 bathrooms, with one bedroom conveniently located on the main level—ideal for guests or a home office. The inviting living room features soaring ceilings and a cozy fireplace, creating the perfect atmosphere for relaxing or entertaining. The light-filled kitchen includes granite countertops, a newer Sub-Zero refrigerator/freezer, double ovens, a large pantry, and a skylight that brings in abundant natural light. Step outside to your private backyard retreat complete with a sparkling in-ground pool, patio space for entertaining, and lush landscaping. With a newer roof, refreshed exterior paint, and a prime location near top-rated schools, shopping, dining, and hiking trails, this move-in-ready home offers comfort, convenience, and classic California living.",
        contactEmail: `info@info.lease`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "miami",
    name: "Miami",
    state: "Florida",
    heroImage: "/miami.avif",
    properties: [
      {
        id: "1",
        category: "Miami Beach Homes",
        slug: generateRandomSlug(),
        address: "1524 Biarritz Dr, Miami Beach, FL 33141",
        pricePerMonth: 8490,
        bedrooms: 4,
        bathrooms: 4,
        sqft: 2406,
        images: [
          "/properties/miami-2-1.webp",
          "/properties/miami-2-2.webp",
          "/properties/miami-2-3.webp",
          "/properties/miami-2-4.webp",
          "/properties/miami-2-5.webp",
          "/properties/miami-2-6.webp",
        ],
        amenities: [
          "4 Beds",
          "4 Baths",
          "Cozy Fireplace",
          "Updated Appliances",
          "Grassy Yard & Mature Trees",
          "Large Impact Windows",
          "Exotic Tile Flooring",
          "Guest Cottage with Private Entrance",
        ],
        description:
          "This charming multi-family Miami Beach home blends modern convenience with classic style. The main residence offers three spacious bedrooms, 2.5 baths, a cozy fireplace, and a bright open floor plan with exotic tile flooring and large impact windows. The separate cottage is fully self-contained, ideal for guests or rental income, with its own kitchen and bathroom. The property is steps from shopping, parks, and transportation in the sought-after Biarritz Drive neighborhood.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Miami Beach Homes",
        slug: generateRandomSlug(),
        address: "1368 Normandy Dr, Miami Beach, FL 33141",
        pricePerMonth: 10683,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2190,
        images: [
          "/properties/miami-1-1.webp",
          "/properties/miami-1-2.webp",
          "/properties/miami-1-3.webp",
          "/properties/miami-1-4.webp",
          "/properties/miami-1-5.webp",
          "/properties/miami-1-6.webp",
        ],
        amenities: [
          "4 Beds",
          "3 Baths",
          "Private Pool",
          "Sunlit Open-Concept Layout",
          "Vaulted Ceilings",
          "Kitchen Island",
          "Clear Impact Glass Windows",
          "Furnished",
          "Tropical Garden Views",
        ],
        description:
          "Nestled in the coveted Isle of Normandy neighborhood of Miami Beach, this 1938 gem combines tropical charm with modern elegance. The sunlit open-concept home features four bedrooms, three bathrooms, vaulted ceilings, a kitchen island, and clear impact glass windows. Enjoy resort-style living with a private pool surrounded by swaying palms, a deck and patio perfect for entertaining, and a garden oasis. Ideal for those seeking a serene retreat just minutes from Miami’s vibrant city center and pristine beaches.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "nashville",
    name: "Nashville",
    state: "Tennessee",
    heroImage: "/nashville.avif",
    properties: [
      {
        id: "1",
        category: "Nashville Homes",
        slug: generateRandomSlug(),
        address: "1026 Jefferson St, Nashville, TN 37208",
        pricePerMonth: 6938,
        bedrooms: 4,
        bathrooms: 5,
        sqft: 2231,
        images: [
          "/properties/nashville-1-1.webp",
          "/properties/nashville-1-2.webp",
          "/properties/nashville-1-3.webp",
          "/properties/nashville-1-4.webp",
          "/properties/nashville-1-5.webp",
        ],
        amenities: [
          "4 Beds",
          "5 Baths",
          "Covered Terrace",
          "Private Rooftop Retreat",
          "Sweeping Downtown Skyline Views",
          "Turnkey Short-Term Rental Ready",
          "High Ceilings & Open Floorplan",
          "Smart Thermostat & Walk-In Closets",
          "Association Pool & Gated Community",
        ],
        description:
          "Located in the acclaimed Alora Nashville community, this 2024 residence offers a fully operating short-term rental with lifestyle and investment value. The home features four bedrooms, five bathrooms, a private rooftop with covered terrace and firepit, sweeping city views, and high-end finishes. Professionally curated interiors ensure a turnkey experience, while its prime location near Broadway, Amazon, and Oracle East Bank provides both convenience and exclusivity.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Nashville Homes",
        slug: generateRandomSlug(),
        address: "4228 Stone Hall Blvd, Hermitage, TN 37076",
        pricePerMonth: 4025,
        bedrooms: 4,
        bathrooms: 4,
        sqft: 3145,
        images: [
          "/properties/nashville-2-1.webp",
          "/properties/nashville-2-2.webp",
          "/properties/nashville-2-3.webp",
          "/properties/nashville-2-4.webp",
          "/properties/nashville-2-5.webp",
        ],
        amenities: [
          "4 Beds",
          "4 Baths",
          "Corner Lot",
          "Custom Double-Sided Fireplace",
          "Walk-In Closets",
          "High Ceilings & Open Floorplan",
          "Gourmet Kitchen with Walk-In Pantry",
          "Backyard Firepit & Deck",
          "Community Pool & Playground",
        ],
        description:
          "This 2016 Hermitage home blends luxury design and everyday functionality. Featuring four bedrooms, four bathrooms, a main-level primary suite, and a bonus room, the property is ideal for family living or entertaining. The backyard offers a deck, stone patio, and firepit, while community amenities include a pool, park, and playground. Thoughtful craftsmanship throughout, including coffered ceilings and a double-sided fireplace, ensures a balance of comfort and style in a sought-after location.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "philadelphia",
    name: "Philadelphia",
    state: "Pennsylvania",
    heroImage: "/philly.avif",
    properties: [
      {
        id: "1",
        category: "Philadelphia Homes",
        slug: generateRandomSlug(),
        address: "819 N Orkney St, Philadelphia, PA 19123",
        pricePerMonth: 5841,
        bedrooms: 3,
        bathrooms: 4,
        sqft: 3200,
        images: [
          "/properties/philly-1-1.webp",
          "/properties/philly-1-2.webp",
          "/properties/philly-1-3.webp",
          "/properties/philly-1-4.webp",
          "/properties/philly-1-5.webp",
        ],
        amenities: [
          "3 Beds",
          "4 Baths",
          "2-Car Attached Garage",
          "Gated Community",
          "Walk-In Closets",
          "Upgraded Countertops & Kitchen Island",
          "Finished Basement",
          "Recessed Lighting & Ceiling Fans",
          "Fireplace",
        ],
        description:
          "Located in Northern Liberties’ exclusive SEVENTEEN gated townhome enclave, this 2016 townhouse offers 3,200 sqft of living space with three bedrooms and four bathrooms. The home features a modern, striking façade, finished basement, and two-car garage. Interior highlights include walk-in closets, recessed lighting, upgraded countertops, kitchen island, and a cozy fireplace, combining style, comfort, and urban convenience.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Philadelphia Homes",
        slug: generateRandomSlug(),
        address: "1110 Cypress St, Philadelphia, PA 19107",
        pricePerMonth: 9616,
        bedrooms: 4,
        bathrooms: 6,
        sqft: 4502,
        images: [
          "/properties/philly-2-1.webp",
          "/properties/philly-2-2.webp",
          "/properties/philly-2-3.webp",
          "/properties/philly-2-4.webp",
          "/properties/philly-2-5.webp",
        ],
        amenities: [
          "4 Beds",
          "6 Baths",
          "Attached Two-Car Garage",
          "Rooftop Deck with City Views",
          "Private Primary Suite Retreat",
          "Oversized Walk-In Closets",
          "Open-Concept Layout",
          "Quartzite Countertops",
          "Smart Home Technology",
        ],
        description:
          "Introducing Cypress Commons in Washington Square West, a luxury collection of new-construction townhomes. Built in 2025, this 4,502 sqft home features four bedrooms, six bathrooms, an attached two-car garage, private rooftop deck, open-concept living areas, chef’s kitchen with quartzite countertops, and smart-home features. Ideal for modern urban living with proximity to historic landmarks, dining, and entertainment.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "phoenix",
    name: "Phoenix",
    state: "Arizona",
    heroImage: "/phoenix.avif",
    properties: [
      {
        id: "1",
        category: "Phoenixville Homes",
        slug: generateRandomSlug(),
        address: "228-230 Church St, Phoenixville, PA 19460",
        pricePerMonth: 4446,
        bedrooms: 8,
        bathrooms: 4,
        sqft: 4000,
        images: [
          "/properties/phoenix-1-1.webp",
          "/properties/phoenix-1-2.webp",
          "/properties/phoenix-1-3.webp",
          "/properties/phoenix-1-4.webp",
          "/properties/phoenix-1-5.webp",
        ],
        amenities: [
          "8 Beds",
          "4 Baths",
          "Secured Fenced Yard",
          "Private Rear Garden",
          "In-Unit Laundry",
          "Electric Cooking",
          "Central Air",
          "Mixed-Use Zoning",
          "Income-Producing Units",
        ],
        description:
          "Income-producing four-unit quadruplex in Phoenixville Borough featuring two expansive four-bedroom, two-level units, one three-bedroom street-level unit, and one garden-style efficiency apartment. Each unit is separately metered and leased month-to-month. Excellent location near Phoenixville’s vibrant restaurants, breweries, and cultural attractions, with easy access to Valley Forge National Park and King of Prussia Mall. A solid investment opportunity in a desirable rental market.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Phoenixville Homes",
        slug: generateRandomSlug(),
        address: "Cambridge Plan, Phoenixville Heights, Phoenixville, PA 19460",
        pricePerMonth: 3175,
        bedrooms: 3,
        bathrooms: 4,
        sqft: 1989,
        images: [
          "/properties/phoenix-2-1.webp",
          "/properties/phoenix-2-2.webp",
          "/properties/phoenix-2-3.webp",
          "/properties/phoenix-2-4.webp",
          "/properties/phoenix-2-5.webp",
        ],
        amenities: [
          "3 Beds",
          "4 Baths",
          "Two-Car Garage",
          "Top Floor Owner’s Suite",
          "Balcony & Deck",
          "Spacious Great Room",
          "Modern Kitchen",
          "Open-Concept Living",
          "New Construction",
        ],
        description:
          "The Cambridge Plan at Phoenixville Heights is a new 3-bedroom, 4-bath townhouse with 1,989 sqft of livable space. Features include a recreation room on the first floor, open-concept main living areas with modern kitchen and dining, balcony and deck for seamless indoor-outdoor living, and a private owner’s suite on the top floor. This new-construction home offers optimal layout, privacy, and a two-car garage, all in a thriving Phoenixville community near downtown amenities.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "pittsburgh",
    name: "Pittsburgh",
    state: "Pennsylvania",
    heroImage: "/pitts.avif",
    properties: [
      {
        id: "1",
        category: "Pittsburgh Homes",
        slug: generateRandomSlug(),
        address: "88 Waterfront Dr, Pittsburgh, PA 15222",
        pricePerMonth: 11879,
        bedrooms: 5,
        bathrooms: 6,
        sqft: 4318,
        images: [
          "/properties/pitts-1-1.webp",
          "/properties/pitts-1-2.webp",
          "/properties/pitts-1-3.webp",
          "/properties/pitts-1-4.webp",
          "/properties/pitts-1-5.webp",
        ],
        amenities: [
          "Waterfront Residence",
          "5 Beds",
          "6 Baths",
          "Open Concept Living Spaces",
          "Centrally Built-In Speaker System",
          "Elevator",
          "Newer Decks",
          "Private Oasis",
          "Granite Countertops",
          "Modern Appliances",
          "Community Tennis & Docks",
        ],
        description:
          "Stunning waterfront townhouse with four floors of luxurious living, private end unit for maximum privacy, and breathtaking views of the water and city skyline. Features include open-concept living, centrally built-in speaker system, zone-specific heating and cooling, granite kitchen with modern appliances and wine fridge, gorgeous tiled bathrooms, elevator access, and newer decks. Located along the Three Rivers Heritage Trail with community amenities and easy access to downtown Pittsburgh attractions.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Pittsburgh Homes",
        slug: generateRandomSlug(),
        address: "907 Jefferson Dr, Pittsburgh, PA 15229",
        pricePerMonth: 2142,
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1026,
        images: [
          "/properties/pitts-2-1.webp",
          "/properties/pitts-2-2.webp",
          "/properties/pitts-2-3.webp",
          "/properties/pitts-2-4.webp",
          "/properties/pitts-2-5.webp",
        ],
        amenities: [
          "3 Beds",
          "2 Baths",
          "Single-Family Ranch Style",
          "Garage & Workshop",
          "Pristine Walk-Up Attic",
          "Lovely Gardens",
          "Huge Laundry Room",
          "Lead Windows & Sidelights",
          "Freshly Painted",
          "Gas Fireplace",
        ],
        description:
          "Beautifully maintained 3-bedroom, 2-bath ranch in North Hills Estates. Features include hardwood floors, trimline custom windows, large laundry room, workshop in garage, fruit cellar, gas fireplace, and covered back porch. Originally built in 1952, this home blends classic charm with modern upgrades. Located in a family-friendly community with year-round activities and parks nearby.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "portland",
    name: "Portland",
    state: "Oregon",
    heroImage: "/portland.avif",
    properties: [
      {
        id: "1",
        category: "Portland Homes",
        slug: generateRandomSlug(),
        address: "2725 SW Sherwood Dr, Portland, OR 97201",
        pricePerMonth: 11066,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 3978,
        images: [
          "/properties/port-1-1.webp",
          "/properties/port-1-2.webp",
          "/properties/port-1-3.webp",
          "/properties/port-1-4.webp",
          "/properties/port-1-5.webp",
        ],
        amenities: [
          "Forest Setting",
          "Highly Functional Layout",
          "Ample Storage",
          "Sunlit Rooms",
          "Several Bonus Areas",
          "Dreamy Walk-In Closet",
          "2 Fireplaces",
          "Daylight Finished Basement",
          "Covered Deck & Patio",
          "Spa Bath",
          "Territorial & Wooded Views",
          "3-Car Attached Garage",
        ],
        description:
          "Landmark architectural masterpiece in Portland Heights designed by Robert Thompson of TVA Architects. This NW Contemporary residence offers serene, sunlit spaces with multiple balconies, bonus areas, luxurious primary suite with walk-in closet and sauna, modern kitchen with built-in appliances, two fireplaces, and a finished daylight basement. Nestled on a private, wooded 0.25-acre lot while minutes from downtown Portland, OHSU, and Council Crest Park.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "Portland Homes",
        slug: generateRandomSlug(),
        address: "2211 SW 1st Ave Unit 1502, Portland, OR 97201",
        pricePerMonth: 5232,
        bedrooms: 3,
        bathrooms: 2,
        sqft: 2247,
        images: [
          "/properties/port-2-1.webp",
          "/properties/port-2-2.webp",
          "/properties/port-2-3.webp",
          "/properties/port-2-4.webp",
          "/properties/port-2-5.webp",
        ],
        amenities: [
          "Electric Fireplace",
          "High-End Miele Appliances",
          "Seamless Entertaining Space",
          "Separate Toilet & Shower",
          "Soaring Ceilings",
          "Granite Countertops",
          "Panoramic River & Mountain Views",
          "Balconies in Bedrooms",
          "Condo Elevator & Concierge",
          "1-Car Secured Garage",
          "$1,945/mo HOA",
        ],
        description:
          "Rare American Plaza Towers condo with sweeping panoramic views of the Willamette River and iconic peaks. East-facing living spaces capture morning light, while west-facing bedrooms enjoy stunning sunsets. Features include gourmet kitchen with built-in appliances, granite countertops, balconies, electric fireplaces, high ceilings, and spacious suites. HOA amenities include concierge, gym, pool, spa, and maintenance services.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "san-diego",
    name: "San Diego",
    state: "California",
    heroImage: "/sandiego.avif",
    properties: [
      {
        id: "1",
        category: "San Diego Homes",
        slug: generateRandomSlug(),
        address: "11479 Duenda Rd, San Diego, CA 92127",
        pricePerMonth: 11002,
        bedrooms: 5,
        bathrooms: 5,
        sqft: 3650,
        images: [
          "/properties/diego-1-1.webp",
          "/properties/diego-1-2.webp",
          "/properties/diego-1-3.webp",
          "/properties/diego-1-4.webp",
          "/properties/diego-1-5.webp",
        ],
        amenities: [
          "Expansive Backyard",
          "Extensive Hardscaping",
          "Grand Primary Suite",
          "Private Sanctuary",
          "Tranquil Multi-Tiered Pond",
          "Cozy Breakfast Nook",
          "Versatile Floor Plan",
          "2 Fireplaces",
          "Vaulted Ceilings",
          "High-End Appliances",
          "Community Pool",
          "2-Car Attached Garage",
          "Westwood Club HOA $57/mo",
        ],
        description:
          "Experience tropical luxury in this stunning Westwood home rebuilt in 2008. Open-concept living with vaulted ceilings, gourmet kitchen, cozy breakfast nook, and versatile main-level bedroom. The grand primary suite and three additional bedrooms upstairs offer comfort and privacy. Entertainer’s backyard features pergola, hardscaping, and multi-tiered pond. Nestled in the desirable Rancho Bernardo community with access to Westwood Club amenities and top-rated Poway Unified School District.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "2",
        category: "San Diego Homes",
        slug: generateRandomSlug(),
        address: "8477 El Paseo Grande, La Jolla, CA 92037",
        pricePerMonth: 7077,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 3116,
        images: [
          "/properties/diego-2-1.webp",
          "/properties/diego-2-2.webp",
          "/properties/diego-2-3.webp",
          "/properties/diego-2-4.webp",
          "/properties/diego-2-5.webp",
        ],
        amenities: [
          "Glowing Fireplace",
          "Chef-Ready Kitchen",
          "Open-Plan Layout",
          "Primary Suite with Fireplace",
          "Expansive Glass & Decks",
          "Ocean Views",
          "Pool & Spa",
          "Two-Car Attached Garage",
          "High-End Wood & Tile Flooring",
          "Turnkey Pacaso Co-Ownership",
        ],
        description:
          "New co-ownership opportunity in La Jolla Shores with this professionally managed Pacaso home. Remodeled with clean lines, expansive glass, and indoor-outdoor living spaces. Features chef-ready kitchen, glowing fireplace, primary suite with fireplace, balconies with ocean views, poolside terrace, and turnkey ownership for luxury seaside living. Two-car attached garage, central air, and high-end finishes complete the package.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "san-francisco",
    name: "San Francisco",
    state: "California",
    heroImage: "/francisco.jpg",
    properties: [
      {
        id: "sf-1",
        category: "San Francisco Homes",
        slug: generateRandomSlug(),
        address: "1551 20th Ave, San Francisco, CA 94122",
        pricePerMonth: 11212,
        bedrooms: 6,
        bathrooms: 5,
        sqft: 3462,
        images: [
          "/properties/sf-1-1.webp",
          "/properties/sf-1-2.webp",
          "/properties/sf-1-3.webp",
          "/properties/sf-1-4.webp",
          "/properties/sf-1-5.webp",
        ],
        amenities: [
          "Ocean Views",
          "Fully Detached",
          "Multi-Residence Flexibility",
          "2-Car Garage + 1 Carport",
          "Vacant Owner’s Unit",
          "Tenant-Occupied Front Unit for Immediate Income",
          "Close to Golden Gate Park, Ocean Beach, and Sunset Reservoir Park",
          "Nearby Irving & Judah Dining and Cafés",
          "Access to N-Judah MUNI Line",
        ],
        description:
          "Fully detached Central Sunset residence offering multi-residence living and strong upside potential. Owner’s unit features 2 BD/2 BA with ocean views and comes vacant, along with a 2-car garage. Lower unit 1551-A also 2 BD/2 BA and vacant. Front unit tenant-occupied for income. Ideal for multi-generational living, owner-occupancy with rental income, or leasing all units. Classic 1924 property on 3,600 sq ft lot with 3,462 sq ft living space. Prime location near Golden Gate Park, 16th Avenue Mosaic Stairway, Ocean Beach, and local amenities.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "sf-2",
        category: "San Francisco Homes",
        slug: generateRandomSlug(),
        address: "1711 23rd Ave, San Francisco, CA 94122",
        pricePerMonth: 6981,
        bedrooms: 3,
        bathrooms: 2,
        sqft: 1760,
        images: [
          "/properties/sf-2-1.webp",
          "/properties/sf-2-2.webp",
          "/properties/sf-2-3.webp",
          "/properties/sf-2-4.webp",
          "/properties/sf-2-5.webp",
        ],
        amenities: [
          "Wood Burning Fireplace",
          "Two-Car Tandem Garage",
          "Formal Dining Room & Entry",
          "Updated Kitchen with Breakfast Area & Granite Counters",
          "Vaulted Ceilings in Living Room",
          "Legal Family Room on Garage Level",
          "Hardwood Floors",
          "Close to Noriega & Irving Commercial Corridors",
          "Easy Access to N-Judah MUNI Line",
        ],
        description:
          "1927 Spanish Mediterranean Doelger-built home in Central Sunset. Main living level features formal entry, living room with vaulted ceilings, wood burning fireplace, dining room, updated kitchen with breakfast area, and two rear bedrooms with split bath. Garage level includes legal family room, bath, tandem 2-car garage, and laundry area. Perfect first-time market listing after 55 years. Recent interior/exterior paint, refinished hardwood floors, and staged for viewing. Prime location near shopping, dining, and transit.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "san-jose",
    name: "San Jose",
    state: "California",
    heroImage: "/jose.avif",
    properties: [
      {
        id: "jose-1",
        category: "San Jose Homes",
        slug: generateRandomSlug(),
        address: "536 Curie Dr, San Jose, CA 95123",
        pricePerMonth: 11266,
        bedrooms: 4,
        bathrooms: 2,
        sqft: 1933,
        images: [
          "/properties/jose-1-1.webp",
          "/properties/jose-1-2.webp",
          "/properties/jose-1-3.webp",
          "/properties/jose-1-4.webp",
          "/properties/jose-1-5.webp",
        ],
        amenities: [
          "Sparkling Pool & Outdoor Spa",
          "Private Backyard Oasis",
          "Mountain Views",
          "Wood-Burning Fireplace",
          "Hardwood Floors Throughout",
          "Open Beam Wood Ceilings",
          "Planted Entry Courtyard",
          "Outdoor Kitchen & Large Patio",
          "2-Car Garage + Extra Parking",
          "Energy Efficient Dual Pane Windows",
        ],
        description:
          "Stunning single-level home with breathtaking mountain views, private backyard oasis, and sparkling pool/spa. Perfect for entertaining with open beam ceilings, hardwood floors, outdoor kitchen, and landscaped entry courtyard. Cozy family room with wood-burning fireplace and spacious master suite leading to pool. Impeccably maintained, move-in ready. 2-car garage with extra parking.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "jose-2",
        category: "San Jose Homes",
        slug: generateRandomSlug(),
        address: "6460 Standridge Ct, San Jose, CA 95123",
        pricePerMonth: 10827,
        bedrooms: 4,
        bathrooms: 3,
        sqft: 2386,
        images: [
          "/properties/jose-2-1.webp",
          "/properties/jose-2-2.webp",
          "/properties/jose-2-3.webp",
          "/properties/jose-2-4.webp",
          "/properties/jose-2-5.webp",
        ],
        amenities: [
          "Quiet Court Location at Base of Santa Teresa Hills",
          "Mountain Views",
          "Two-Story Foyer & High Ceilings",
          "Two Fireplaces (Living Room & Family Room)",
          "Granite Countertops & Double Oven in Kitchen",
          "Pergola in Backyard with Fruit Trees",
          "Primary Suite with French Doors & Dual Closets",
          "En Suite Bath with Dual Sinks & Walk-In Shower",
          "3-Car Attached Garage",
          "Recessed Lighting & Dual Pane Windows",
        ],
        description:
          "Contemporary 4-bedroom, 2.5-bath home tucked away on a quiet court near Santa Teresa Hills. Spacious 2,386 sq ft with high ceilings, granite kitchen, and two fireplaces. Backyard with pergola, fruit trees, and mountain views. Primary suite with French doors and en suite bath. Excellent storage with 3-car garage. Modern updates include new laminate flooring, carpet, and dual-pane windows. Conveniently located near highways, shopping, and Santa Teresa High School.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
  {
    id: "santa-monica",
    name: "Santa Monica",
    state: "California",
    heroImage: "/monica.avif",
    properties: [
      {
        id: "monica-1",
        category: "Santa Monica Homes",
        slug: generateRandomSlug(),
        address: "2425 20th St #B, Santa Monica, CA 90405",
        pricePerMonth: 11650,
        bedrooms: 3,
        bathrooms: 3,
        sqft: 1699,
        images: [
          "/properties/monica-1-1.webp",
          "/properties/monica-1-2.webp",
          "/properties/monica-1-3.webp",
          "/properties/monica-1-4.webp",
          "/properties/monica-1-5.webp",
        ],
        amenities: [
          "Custom Kitchens with Professional-Grade Appliances",
          "Expansive Walls of Glass",
          "Breakfast Bars",
          "Sculpted Stone Countertops",
          "Voluminous Open-Plan Living Spaces",
          "Three Bedroom Suites Including Primary Retreat",
          "Spa-Inspired Primary Bath with Dual Vanities & Walk-In Shower",
          "Flexible Office or Studio Space",
          "Private Attached 2-Car Garage",
          "Contemporary Coastal Architecture",
        ],
        description:
          "Trio, an architecturally refined collection of three townhomes in Santa Monica's Sunset Park. Open-plan living spaces with natural light, custom kitchens, and three bedroom suites. Primary suite includes spa-inspired bath and walk-in shower. Flexible office/studio space and private attached garage. Contemporary design, moments from Santa Monica dining, boutiques, and beach.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
      {
        id: "monica-2",
        category: "Santa Monica Homes",
        slug: generateRandomSlug(),
        address: "1119 23rd St Unit 7, Santa Monica, CA 90403",
        pricePerMonth: 9851,
        bedrooms: 3,
        bathrooms: 3,
        sqft: 2046,
        images: [
          "/properties/monica-2-1.webp",
          "/properties/monica-2-2.webp",
          "/properties/monica-2-3.webp",
          "/properties/monica-2-4.webp",
          "/properties/monica-2-5.webp",
        ],
        amenities: [
          "Private Ground-Floor Access",
          "Rooftop Patio",
          "Light-Filled Atrium Patio",
          "Large Finished Flex Space & Multiple Bonus Rooms",
          "Double Vanity Dressing Area",
          "Wet Bar",
          "3 Levels of Living Space",
          "Chef’s Kitchen and Dining Area",
          "Attached 2-Car Garage with Built-In Storage",
          "Close to Schools, Dining, Shopping & Beaches",
        ],
        description:
          "Tri-level condo living like a single-family home, 23 blocks from the beach. Multiple bonus rooms and flex space for office or sleeping. Primary suite with soaring ceilings, double vanity, and private rooftop patio. Entry-level atrium patio, living/dining areas, wet bar. Attached 2-car garage. Modern Santa Monica lifestyle with convenient location near shopping, dining, schools, and the iconic beach.",
        contactEmail: `info@etoric.llc`,
        contactPhone: "+1 (915) 999-8349",
      },
    ],
  },
];
